Feature/1895 wcb do allow to pass certificate on tagtogpy not only true or false
tagtog/tagtog-doc pull request #19
Opened 2020-10-06 06:14 UTC by waldemar-tagtog

2020-10-06 08:07 UTC, juanmirocks requested changes
Good job. Please look at the suggestions.

2020-10-06 08:07 UTC, juanmirocks commented on tagtog.py
> +            return x
```suggestion
        if os.path.isfile(x):
            return x
        else:
            return (x.lower() in {"yes", "true", "t", "y", "1"})
```

2020-10-07 04:22 UTC, waldemar-tagtog commented on tagtog.py
> +            return x
I think the proposed solution is going in wrong direction. Because:
1. If the user unwillingly write wrong path then the system will accept the final value as false (most probably), instead of returns just an error.
2. When the user put wrong value for true, say "tru" the system accepts it as a false, instead of informing user it is unknown value.
I would only change my "return x" into adding the file existence check, like:

if x.lower() in {'yes', 'true', 't', 'y', '1'}:
    return True
elif x.lower() in {'no', 'false', 'f', 'n', '0'}:
    return False
elif os.path.isfile(x):
    return x
else
    raise Exception("Sorry, I do not understand your parameter for verify_ssl, Allow values: bla, bla... or read documentation")

2020-10-07 08:28 UTC, juanmirocks commented on tagtog.py
> +            return x
Good thinking! Raising an exception is certainly more secure for the user. So I like your proposition.

I would still put the `if os.path.isfile(x)` check the first one. Because if it's a path, we avoid lowering the case of the string multiple times.

2020-10-07 13:07 UTC, juanmirocks commented on tagtog.py
> +            return x
If python has a concept of `IllegalArgumentException` (like java's), write down a more specific Exception type.

2020-10-07 20:02 UTC, waldemar-tagtog commented on tagtog.py
> +            return x
I think that the ValueError would be most similar to the IlligalArgumentException and the way how the exception is throwing suggests me to also to change the function name.

2020-10-08 11:19 UTC, juanmirocks requested changes
Please apply the suggested changes and we are done 👍

2020-10-08 11:19 UTC, juanmirocks commented on tagtog.py
> +        parser.add_argument("--verify_ssl", type=parse_verify_ssl_argument, default=True, help="(Optional) Choose to verify and how or not verify the ssl certificate of the endpoint domain when makin
```suggestion
        parser.add_argument("--verify_ssl", type=parse_verify_ssl_argument, default=True, help="(Optional) Choose to verify, and if so how, or not to verify the SSL/TLS certificate of the endpoint domain when making http requests. Possible values: True (default), False, or a path with trusted SSL/TLS certificate/s (either a single file or a directory).")
```

2020-10-08 11:19 UTC, juanmirocks commented on tagtog.py
> +        if os.path.isfile(x):
My bad, you were right @waldemar-tagtog 

The path can be generalized to be either a single file or a directory of trusted certificates ([Requests documentation here](https://requests.readthedocs.io/en/master/user/advanced/#ssl-cert-verification))

Therefore, let's just check if the path exists at all:

```suggestion
        if os.path.exists(x):
```

2020-10-08 11:19 UTC, juanmirocks commented on tagtog.py
> +            raise ValueError
Great. This is good.

2020-10-09 05:42 UTC, waldemar-tagtog commented on tagtog.py
> +            raise ValueError
the 2 changes done

2020-10-09 08:23 UTC, juanmirocks approved these changes
Done ✅

2020-10-09 08:23 UTC, juanmirocks commented on tagtog.py
> +            raise ValueError
Great. All good from my side

2020-10-09 08:24 UTC, juanmirocks commented
Fix #17

2020-10-09 08:26 UTC, merged